/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expertsystem;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.ImageIcon;
import java.util.Map;
import javax.swing.JOptionPane;
import org.jpl7.Query;
import org.jpl7.Term;

/**
 *
 * @author JKBO
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    /*Designers vars*/
    public int xMouse;
    int yMouse;
    StringSelection stringSelection = null;
    
    public home() {
        initComponents();
        
        setLocationRelativeTo(null);
        String t1 = "consult('C:/Users/joaqu/Documents/Prolog/verbos.pl')";
        Query q1 = new Query(t1);
        System.out.println(t1 + " " + (q1.hasSolution() ? "conectado" : "no conectado"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        btn_about = new javax.swing.JLabel();
        btn_close = new javax.swing.JLabel();
        lbl_subtitle = new javax.swing.JLabel();
        lbl_title = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        txt_word = new javax.swing.JTextField();
        hint_pasado1 = new javax.swing.JLabel();
        hint_pasado = new javax.swing.JLabel();
        hint_infinitivo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_translate = new javax.swing.JLabel();
        lbl_pp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_infinitivo = new javax.swing.JLabel();
        lbl_pasado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TeacherBot");
        setLocationByPlatform(true);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(778, 524));
        setMinimumSize(new java.awt.Dimension(778, 524));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(778, 524));
        setResizable(false);
        setSize(new java.awt.Dimension(778, 524));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setMaximumSize(new java.awt.Dimension(778, 524));
        body.setMinimumSize(new java.awt.Dimension(778, 524));

        header.setBackground(new java.awt.Color(104, 109, 224));
        header.setPreferredSize(new java.awt.Dimension(500, 712));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_about.setBackground(new java.awt.Color(104, 109, 224));
        btn_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/HD_about_24px.png"))); // NOI18N
        btn_about.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_about.setOpaque(true);
        btn_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_aboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_aboutMouseExited(evt);
            }
        });
        header.add(btn_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, -1, -1));

        btn_close.setBackground(new java.awt.Color(104, 109, 224));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/HD_close_32px.png"))); // NOI18N
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_close.setOpaque(true);
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_closeMouseExited(evt);
            }
        });
        header.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 0, -1, -1));

        lbl_subtitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_subtitle.setForeground(new java.awt.Color(204, 204, 255));
        lbl_subtitle.setText("Sistema Experto");
        header.add(lbl_subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 171, -1, -1));

        lbl_title.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("TeacherBot");
        header.add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 116, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/header-bg.png"))); // NOI18N
        header.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 800, 213));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_word.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txt_word.setForeground(new java.awt.Color(0, 51, 51));
        txt_word.setText("verbo");
        txt_word.setBorder(null);
        txt_word.setOpaque(false);
        txt_word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_wordActionPerformed(evt);
            }
        });
        content.add(txt_word, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 600, 40));

        hint_pasado1.setBackground(new java.awt.Color(255, 255, 255));
        hint_pasado1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        hint_pasado1.setForeground(new java.awt.Color(142, 68, 173));
        hint_pasado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hint_pasado1.setText("Pasado Participio");
        hint_pasado1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hint_pasado1.setOpaque(true);
        content.add(hint_pasado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 95, 110, 20));

        hint_pasado.setBackground(new java.awt.Color(255, 255, 255));
        hint_pasado.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        hint_pasado.setForeground(new java.awt.Color(230, 126, 34));
        hint_pasado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hint_pasado.setText("Pasado");
        hint_pasado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hint_pasado.setOpaque(true);
        content.add(hint_pasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 95, 60, 20));

        hint_infinitivo.setBackground(new java.awt.Color(255, 255, 255));
        hint_infinitivo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        hint_infinitivo.setForeground(new java.awt.Color(243, 156, 18));
        hint_infinitivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hint_infinitivo.setText("Infinitivo");
        hint_infinitivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hint_infinitivo.setOpaque(true);
        content.add(hint_infinitivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 95, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/line2.png"))); // NOI18N
        content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 620, 10));

        btn_translate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/CT_translator_leave_42px.png"))); // NOI18N
        btn_translate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_translate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_translateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_translateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_translateMouseExited(evt);
            }
        });
        content.add(btn_translate, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        lbl_pp.setBackground(new java.awt.Color(102, 51, 255));
        lbl_pp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_pp.setForeground(new java.awt.Color(142, 68, 173));
        lbl_pp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/pp_leave.png"))); // NOI18N
        lbl_pp.setText("Esperando");
        lbl_pp.setToolTipText("Pasado participio");
        lbl_pp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_pp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_pp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ppMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ppMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ppMouseExited(evt);
            }
        });
        content.add(lbl_pp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 200, 150));

        jLabel3.setBackground(new java.awt.Color(102, 51, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Palabra a traducir");
        content.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        lbl_infinitivo.setBackground(new java.awt.Color(102, 51, 255));
        lbl_infinitivo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_infinitivo.setForeground(new java.awt.Color(243, 156, 18));
        lbl_infinitivo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_infinitivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/infinitivo_leave.png"))); // NOI18N
        lbl_infinitivo.setText("Esperando");
        lbl_infinitivo.setToolTipText("Infinitivo");
        lbl_infinitivo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_infinitivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_infinitivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_infinitivoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_infinitivoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_infinitivoMouseExited(evt);
            }
        });
        content.add(lbl_infinitivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 200, 150));

        lbl_pasado.setBackground(new java.awt.Color(102, 51, 255));
        lbl_pasado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbl_pasado.setForeground(new java.awt.Color(230, 126, 34));
        lbl_pasado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/imgs/pasado_leave.png"))); // NOI18N
        lbl_pasado.setText("Esperando");
        lbl_pasado.setToolTipText("Pasado");
        lbl_pasado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_pasado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_pasado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_pasadoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_pasadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_pasadoMouseExited(evt);
            }
        });
        content.add(lbl_pasado, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 200, 150));

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Haz Clic para copiar");
        content.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 120, 20));

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );

        getContentPane().add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - this.xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse  = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void btn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseEntered
        this.btn_close.setBackground(new Color(231, 76, 60));
    }//GEN-LAST:event_btn_closeMouseEntered

    private void btn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseExited
        this.btn_close.setBackground(new Color(104,109,224));
    }//GEN-LAST:event_btn_closeMouseExited

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        System.exit(1);
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btn_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseClicked
        new About_this().setVisible(true);
    }//GEN-LAST:event_btn_aboutMouseClicked

    private void btn_aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aboutMouseEntered

    private void btn_aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_aboutMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_aboutMouseExited

    private void btn_translateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_translateMouseEntered
        this.btn_translate.setIcon(new ImageIcon(this.getClass().getResource("/assets/imgs/CT_translator_hover_42px.png")));
    }//GEN-LAST:event_btn_translateMouseEntered

    private void btn_translateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_translateMouseExited
        this.btn_translate.setIcon(new ImageIcon(this.getClass().getResource("/assets/imgs/CT_translator_leave_42px.png")));
    }//GEN-LAST:event_btn_translateMouseExited

    private void lbl_infinitivoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_infinitivoMouseEntered
        this.lbl_infinitivo.setIcon(new ImageIcon(this.getClass().getResource("/assets/imgs/infinitivo_hover.png")));
    }//GEN-LAST:event_lbl_infinitivoMouseEntered

    private void lbl_infinitivoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_infinitivoMouseExited
        this.lbl_infinitivo.setIcon(new ImageIcon(this.getClass().getResource("/assets/imgs/infinitivo_leave.png")));
    }//GEN-LAST:event_lbl_infinitivoMouseExited

    private void lbl_pasadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pasadoMouseEntered
        this.lbl_pasado.setIcon(new ImageIcon(this.getClass().getResource("/assets/imgs/pasado_hover.png")));
    }//GEN-LAST:event_lbl_pasadoMouseEntered

    private void lbl_pasadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pasadoMouseExited
        this.lbl_pasado.setIcon(new ImageIcon(this.getClass().getResource("/assets/imgs/pasado_leave.png")));
    }//GEN-LAST:event_lbl_pasadoMouseExited

    private void lbl_ppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ppMouseEntered
        this.lbl_pp.setIcon(new ImageIcon(this.getClass().getResource("/assets/imgs/pp_hover.png")));
    }//GEN-LAST:event_lbl_ppMouseEntered

    private void lbl_ppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ppMouseExited
        this.lbl_pp.setIcon(new ImageIcon(this.getClass().getResource("/assets/imgs/pp_leave.png")));
    }//GEN-LAST:event_lbl_ppMouseExited

    private void btn_translateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_translateMouseClicked
        if(this.txt_word.getText().length() >= 2){
            String verbo = this.txt_word.getText();
            try {
                String t2 = "traducir(" + verbo.trim() + ",I,P,F)";
                Query q2 = new Query(t2);
                Map<String, Term>[] map = q2.allSolutions();
                if (map.length <= 0) {
                    JOptionPane.showMessageDialog(null, "No se encontro el verbo");
                } else {
                    for (Map<String, Term> map1 : map) {
                        System.out.println(map1);
                        lbl_infinitivo.setText(map1.get("I").toString());
                        lbl_pasado.setText(map1.get("P").toString());
                        lbl_pp.setText(map1.get("F").toString());
                    }
                }
               } catch (Exception e) {
                   System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_translateMouseClicked

    private void lbl_infinitivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_infinitivoMouseClicked
        this.stringSelection = new StringSelection(this.lbl_infinitivo.getText());
        Clipboard clpbrd = Toolkit.getDefaultToolkit ().getSystemClipboard (); 
        clpbrd.setContents (stringSelection, null);

    }//GEN-LAST:event_lbl_infinitivoMouseClicked

    private void lbl_pasadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pasadoMouseClicked
        this.stringSelection = new StringSelection(this.lbl_pasado.getText());
        Clipboard clpbrd = Toolkit.getDefaultToolkit ().getSystemClipboard (); 
        clpbrd.setContents (stringSelection, null);
    }//GEN-LAST:event_lbl_pasadoMouseClicked

    private void lbl_ppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ppMouseClicked
        this.stringSelection = new StringSelection(this.lbl_pp.getText());
        Clipboard clpbrd = Toolkit.getDefaultToolkit ().getSystemClipboard (); 
        clpbrd.setContents (stringSelection, null);
    }//GEN-LAST:event_lbl_ppMouseClicked

    private void txt_wordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_wordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_wordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPanel body;
    private javax.swing.JLabel btn_about;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel btn_translate;
    private javax.swing.JPanel content;
    private javax.swing.JPanel header;
    private javax.swing.JLabel hint_infinitivo;
    private javax.swing.JLabel hint_pasado;
    private javax.swing.JLabel hint_pasado1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_infinitivo;
    private javax.swing.JLabel lbl_pasado;
    private javax.swing.JLabel lbl_pp;
    private javax.swing.JLabel lbl_subtitle;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_word;
    // End of variables declaration//GEN-END:variables
}
